## Based on https://www.kunalnagar.in/blog/setup-docker-jekyll-dev-environment/

version: '3.6'
services:
  app:
    container_name: dolittle-playbook-environment
    image: jekyll/jekyll:3.8.6
    volumes:
      - ./playbook/:/var/www/html
    working_dir: /var/www/html
    ports:
      - 4000:4000
      - 35729:35729
    environment:
      - "JEKYLL_ENV=docker"
      - "JEKYLL_VERSION=3.8.6"
    restart: always
    command: "jekyll serve --force_polling --livereload --incremental --config _config.yml,_config.docker.yml"